# Site settings
title: mokagio's tech journal
email: giovanni.lodi42@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This place is a collector of random findings regarding little details of the software development craft.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mokagio.github.com/tech-journal" # the base hostname & protocol for your site
twitter_username: mokagio
github_username:  mokagio

# Build settings
markdown: kramdown
highlighter: pygments

kramdown:
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   true

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               main
